export class Constants{
    constructor(){
        this.DatabaseId;
    }
    static CUSTOMER_URL = "https://bbecom-998a.restdb.io/rest/customer";
    static USER_URL = "https://users-de8f.restdb.io/rest/system_jobs";
    static MEDIA_URL = "https://bbecom-998a.restdb.io/media";
    static CUSTOMER_API_KEY = "602276113f9eb665a1689352";
    static USER_API_KEY = "603b382710f29b640ed97bc5";
    static POST_METHOD = "POST";
    static GET_METHOD = "GET";
    static PUT_METHOD = "PUT";
    static DELETE_METHOD = "DELETE";
    static CONTENT_TYPE = "Content-type";
    static DATA_TYPE = "application/json";
    static API_KEY = "x-apikey";
    static ADD_MSG= "Data Added Successfully";
    static DUP_MSG = "Data Already Exists";
    static REGISTER_HTML_ELEMENT = document.getElementById("message");
    static LOGIN_HTML_ELEMENT = document.getElementById("login-message");
    static OTP_HTML_ELEMENT = document.getElementById("otp");
    static FORM_ID = document.getElementById("form-id");
    static FORGOT_PASSWORD_MSG = document.getElementById("error-message");
    static OTP_ERROR = document.getElementById("otp-verify");
    static RESET_ERROR = document.getElementById("reset-error");
    static ITEM_CLASS = "items";
    static DETAIL_CLASS = "details";
    static PRICE_PREFIX = "MRP <sup><del> &#8377; ";
    static PRICE_SUFFIX = " </del></sup> &#8377; ";
    static CART_BUTTON = "cart-btn";
    static ADD_TO_CART = "ADD TO CART";
    static WINDOW_LENGTH = "/html/category.html";
    static FILTER_CLASS = ".filter-check";
    static PRODUCT_CLASS = ".product-container";
    static ALT_TEXT = "*";
    static SHOW_PRODUCT_ITEMS = 20;
    static LOADING = "<h2 class='loading'>Loading...</h2>";
    static LOADING_CLASS = ".loading";
    static BACK_TO_TOP = "<button id='uniqueButton' class='show-more'>Back to top</button>";
    static SHOW_PRODUCT_CLASS = ".show-products";
    static SIDE_BAR_CLASS = ".side-bar";
    static UNIQUE_BUTTON_ID = "#uniqueButton";
    static SHOW_PRODUCT_ID = '#show-products';
    static ENTER_KEY = 13;
    static CART_MAP = new Map();
    static ITEM_LIST = "";
    static NO_PRODUCT_CLASS = ".not-found";
    static NO_PRODUCT_FOUND = "<h2 class='not-found'>Oops.. no such product found.</h2>";
    static DEFAULT_IMAGE_UPLOAD_ID = "60354a809fc7b60c000184c5";
}
